name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "patch"
      remote:
        description: "The remote git where push the bumped version"
        required: true
        default: "origin"
      branch:
        description: "The branch you want to release"
        required: true
        default: "master"
      # npm-dist-tag:
      #   description: "It will add a npm tag to the module, like beta or next"
      #   required: false
      # major:
      #   description: "It will unlock the release of a major release"
      #   required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i releasify --no-save
      - run: cp ./monkey-publish.js ./node_modules/releasify/lib/commands/publish.js
      - run: git config --global user.email "actions@users.noreply.github.com"
      - run: git config --global user.name "${{ github.actor }}"
      - run: npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm whoami
      - run: npm --no-git-tag-version --allow-same-version version ${{ github.event.inputs.semver }}
      - uses: mmarchini-oss/npm-otp-publish@v0.16.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_actor: ${{ github.actor }}
          notifier: console
          npm_token: ${{ secrets.NPM_TOKEN }}
      - name: 'GH release & commit'
        run: |
          ./node_modules/.bin/releasify \
            publish \
            --no-verify \
            --verbose debug \
            --semver ${{ github.event.inputs.semver }} \
            --remote ${{ github.event.inputs.remote }} \
            --branch ${{ github.event.inputs.branch }} \
            --gh-token ${{ secrets.GITHUB_TOKEN }}
